local p4hash = require("p4lua.hash")

describe("xxh3_64", function()
  it("computes a stable hash for known input", function()
    local hash = p4hash.xxh3_64("hello world")
    assert.is_equal(hash, 15296390279056496640)
  end)

  it("computes different hashes for different inputs", function()
    local h1 = p4hash.xxh3_64("abc")
    local h2 = p4hash.xxh3_64("def")
    assert.not_equal(h1, h2)
  end)

  it("computes the same hash for repeated calls", function()
    local a = p4hash.xxh3_64("repeat me")
    local b = p4hash.xxh3_64("repeat me")
    assert.is_equal(a, b)
  end)

  it("returns a number", function()
    local hash = p4hash.xxh3_64("123")
    assert.is_number(hash)
  end)
end)
